### ISSUE TITLE
`#define MAX_SYMBOLS_COUNT` - Is this value arbitrary?

### ISSUE THREAD

**Issue by m0nt3-q** [mrubyc/mrubyc#200]
In `src/vm_config.h` the macro variable `MAX_SYMBOLS_COUNT` has a value of 255.

I haven't found anything in the code to provide a concrete reason why it's that number.
Is it just what was set? or does the runtime need it to be no higher than a uint8_t value?
I'm just running into that as an error (`Overflow MAX_SYMBOLS_COUNT`) and I want to know if making it higher will affect anything.

**Comment by kaz0505** [comment]
MAX_SYMBOLS_COUNT is defined as a constant in src/vm_config.h.

The number 255 has no special meaning, but since mruby/c statically allocates entries in the symbol table at VM startup, it determines the size of the table.

MAX_SYMBOLS_COUNT affects the amount of memory consumed by the VM. If you have sufficient memory, you can increase this value.

**Comment by m0nt3-q** [comment]
Thanks for your response.

This information helps, as I did increase it and did not have any issues that came up.
