### ISSUE TITLE
working example on esp

### ISSUE THREAD

**Issue by sp00ck** [mrubyc/mrubyc#77]
Is possible to create any working example for esp (32 or 6628)
For example i have screen ESP32 

- how writing my own text
- how creating web server (meybe temp sensor)

normal example, i get device , compiling program, flashing device = working device ;)

**Comment by hasumikin** [comment]
@sp00ck 
https://github.com/hasumikin/IoT_workshop
This is a hands-on material fot ESP32 + mrubuy/c which I made.
You can try to make from a basic example to a practical circuit with sensors.
You may have some trouble like version inconsistency or inappropriateness of ESP-IDF and/or mruby/c because this hands-on material is slightly old.
I will be very glad if you point them out :)

**Comment by kaz0505** [comment]
Info from @hasumikin is a good example of ESP32 implementation.
